package graph

type SnapshotStrategy string

const (
	SnapshotStrategyScoped       SnapshotStrategy = "snapshot_scoped"
	SnapshotStrategyParentScoped SnapshotStrategy = "snapshot_parent_scoped"
	SnapshotStrategyGlobal       SnapshotStrategy = "global"
	SnapshotStrategyDerived      SnapshotStrategy = "derived"
)

type SnapshotMigrationEntry struct {
	Table          string
	Owner          string
	Strategy       SnapshotStrategy
	Reason         string
	UniqueScope    string
	UpsertScope    string
	CleanupScope   string
	QueryFilter    string
	Implementation string
}

func SnapshotMigrationManifest() []SnapshotMigrationEntry {
	return []SnapshotMigrationEntry{
		{Table: "repositories", Owner: "graph", Strategy: SnapshotStrategyGlobal, Reason: "logical repository identity", UniqueScope: "name", UpsertScope: "repository name", CleanupScope: "operator reset only", QueryFilter: "joined through workspace snapshots for graph facts"},
		{Table: "workspaces", Owner: "graph", Strategy: SnapshotStrategyGlobal, Reason: "workspace metadata", UniqueScope: "slug", UpsertScope: "slug", CleanupScope: "workspace delete", QueryFilter: "direct workspace lookup"},
		{Table: "workspace_repos", Owner: "graph", Strategy: SnapshotStrategyGlobal, Reason: "workspace repo selection metadata", UniqueScope: "workspace_id, repo_name", UpsertScope: "workspace_id, repo_name", CleanupScope: "workspace delete", QueryFilter: "direct workspace lookup"},
		{Table: "repo_snapshots", Owner: "graph", Strategy: SnapshotStrategyScoped, Reason: "snapshot identity table", UniqueScope: "workspace_id, repo_id, sha, generation", UpsertScope: "unpublished generation; atomic selection after requested stages", CleanupScope: "workspace/repo snapshot delete", QueryFilter: "active workspace snapshot set"},
		{Table: "repo_workspace_state", Owner: "graph", Strategy: SnapshotStrategyGlobal, Reason: "legacy default-main compatibility state", UniqueScope: "repo_id", UpsertScope: "repo_id", CleanupScope: "legacy repo reset", QueryFilter: "default-main compatibility only"},
		{Table: "verify_runs", Owner: "api", Strategy: SnapshotStrategyGlobal, Reason: "estate verification telemetry, not indexed code facts", UniqueScope: "id", UpsertScope: "append-only", CleanupScope: "operator retention policy", QueryFilter: "workspace_id and created_at"},
		{Table: "files", Owner: "parser", Strategy: SnapshotStrategyScoped, Reason: "file facts differ by branch", UniqueScope: "snapshot_id, path", UpsertScope: "snapshot_id, path", CleanupScope: "repo_id + snapshot_id", QueryFilter: "file.snapshot_id in active workspace snapshots", Implementation: "InsertFileForSnapshot/DeleteFilesByRepoSnapshot"},
		{Table: "functions", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "function rows belong to snapshot-scoped files", UniqueScope: "file_id, name_canonical, start_line, end_line", UpsertScope: "file_id", CleanupScope: "file cascade", QueryFilter: "join files.snapshot_id"},
		{Table: "classes", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "class rows belong to snapshot-scoped files", UniqueScope: "file_id + class coordinates", UpsertScope: "file_id", CleanupScope: "file cascade", QueryFilter: "join files.snapshot_id"},
		{Table: "interfaces", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "interface rows belong to snapshot-scoped files", UniqueScope: "file_id, name", UpsertScope: "file_id, name", CleanupScope: "file cascade", QueryFilter: "join files.snapshot_id"},
		{Table: "type_aliases", Owner: "extract-ts-intel", Strategy: SnapshotStrategyParentScoped, Reason: "TypeScript type aliases belong to snapshot-scoped files", UniqueScope: "file_id, name", UpsertScope: "file_id", CleanupScope: "file cascade + per-file extractor cleanup", QueryFilter: "join files.snapshot_id"},
		{Table: "hook_calls", Owner: "extract-ts-intel", Strategy: SnapshotStrategyParentScoped, Reason: "hook calls belong to snapshot-scoped files", UniqueScope: "file_id + hook coordinates", UpsertScope: "file_id", CleanupScope: "file cascade + per-file extractor cleanup", QueryFilter: "join files.snapshot_id"},
		{Table: "vue_component_contracts", Owner: "extract-ts-intel", Strategy: SnapshotStrategyParentScoped, Reason: "Vue component contracts belong to snapshot-scoped files", UniqueScope: "file_id, kind, field_name", UpsertScope: "file_id", CleanupScope: "file cascade + per-file extractor cleanup", QueryFilter: "join files.snapshot_id"},
		{Table: "pinia_stores", Owner: "extract-ts-intel", Strategy: SnapshotStrategyParentScoped, Reason: "Pinia store definitions belong to snapshot-scoped files", UniqueScope: "file_id, store_id", UpsertScope: "file_id", CleanupScope: "file cascade + per-file extractor cleanup", QueryFilter: "join files.snapshot_id"},
		{Table: "implementations", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "implementation rows belong to snapshot-scoped classes/interfaces", UniqueScope: "class_id, interface_name", UpsertScope: "class_id, interface_name", CleanupScope: "class cascade", QueryFilter: "join class file snapshot"},
		{Table: "endpoints", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "endpoint rows belong to snapshot-scoped files/functions", UniqueScope: "repo_id + canonical endpoint + file/function identity", UpsertScope: "file_id/handler_function_id", CleanupScope: "file cascade", QueryFilter: "join files.snapshot_id"},
		{Table: "file_imports", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "imports belong to snapshot-scoped files", UniqueScope: "none", UpsertScope: "file_id", CleanupScope: "file cascade", QueryFilter: "join files.snapshot_id"},
		{Table: "function_calls", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "calls belong to snapshot-scoped caller functions", UniqueScope: "caller_function_id call coordinates", UpsertScope: "caller_function_id", CleanupScope: "file/function cascade", QueryFilter: "join caller function file snapshot"},

		{Table: "pending_contains_edges", Owner: "parser", Strategy: SnapshotStrategyScoped, Reason: "pending graph edges are branch-specific", UniqueScope: "snapshot_id, file_id, entity_id", UpsertScope: "snapshot_id", CleanupScope: "repo_id + snapshot_id", QueryFilter: "snapshot_id in active workspace snapshots"},
		{Table: "pending_calls_edges", Owner: "parser", Strategy: SnapshotStrategyScoped, Reason: "pending call edges are branch-specific", UniqueScope: "snapshot_id, caller_id, callee_name, line_number", UpsertScope: "snapshot_id", CleanupScope: "repo_id + snapshot_id", QueryFilter: "snapshot_id in active workspace snapshots"},
		{Table: "pending_imports_edges", Owner: "parser", Strategy: SnapshotStrategyScoped, Reason: "pending import edges are branch-specific", UniqueScope: "snapshot_id, file_id, import_path", UpsertScope: "snapshot_id", CleanupScope: "repo_id + snapshot_id", QueryFilter: "snapshot_id in active workspace snapshots"},
		{Table: "trace_call_edges", Owner: "resolver", Strategy: SnapshotStrategyScoped, Reason: "resolved trace edges are branch-specific", UniqueScope: "derived from snapshot-scoped functions", UpsertScope: "repo_id + snapshot_id rebuild", CleanupScope: "repo_id + snapshot_id", QueryFilter: "snapshot_id in active workspace snapshots"},
		{Table: "trace_interface_impls", Owner: "resolver", Strategy: SnapshotStrategyScoped, Reason: "interface resolution is branch-specific", UniqueScope: "derived from snapshot-scoped classes/interfaces", UpsertScope: "repo_id + snapshot_id rebuild", CleanupScope: "repo_id + snapshot_id", QueryFilter: "snapshot_id in active workspace snapshots"},
		{Table: "http_client_calls", Owner: "parser", Strategy: SnapshotStrategyScoped, Reason: "outbound calls are branch-specific", UniqueScope: "snapshot_id, caller_id, url_pattern, line_number", UpsertScope: "snapshot_id", CleanupScope: "repo_id + snapshot_id", QueryFilter: "snapshot_id in active workspace snapshots"},
		{Table: "sqs_producers", Owner: "parser", Strategy: SnapshotStrategyScoped, Reason: "queue producers are branch-specific", UniqueScope: "snapshot_id, caller_id, queue_name, line_number", UpsertScope: "snapshot_id", CleanupScope: "repo_id + snapshot_id", QueryFilter: "snapshot_id in active workspace snapshots"},
		{Table: "sqs_consumers", Owner: "parser", Strategy: SnapshotStrategyScoped, Reason: "queue consumers are branch-specific", UniqueScope: "snapshot_id, consumer_id, queue_name", UpsertScope: "snapshot_id", CleanupScope: "repo_id + snapshot_id", QueryFilter: "snapshot_id in active workspace snapshots"},
		{Table: "resource_aliases", Owner: "parser", Strategy: SnapshotStrategyScoped, Reason: "config/env aliases are branch-specific resource resolution facts", UniqueScope: "snapshot_id, file_id, alias_key, alias_value, alias_kind", UpsertScope: "snapshot_id", CleanupScope: "repo_id + snapshot_id", QueryFilter: "snapshot_id in active workspace snapshots"},
		{Table: "repository_entities", Owner: "parser", Strategy: SnapshotStrategyScoped, Reason: "repository/entity mappings are branch-specific", UniqueScope: "snapshot_id, file_id, repository_name, entity_name", UpsertScope: "snapshot_id", CleanupScope: "repo_id + snapshot_id", QueryFilter: "snapshot_id in active workspace snapshots"},
		{Table: "data_accesses", Owner: "parser", Strategy: SnapshotStrategyScoped, Reason: "data accesses are branch-specific", UniqueScope: "snapshot_id, caller_id, entity_name, access, line_number", UpsertScope: "snapshot_id", CleanupScope: "repo_id + snapshot_id", QueryFilter: "snapshot_id in active workspace snapshots"},
		{Table: "ibmi_exports", Owner: "parser", Strategy: SnapshotStrategyScoped, Reason: "IBMi exported symbols are branch-specific resolver facts", UniqueScope: "snapshot_id, file_id, function_id, export_name, object_name, source_type, line_number", UpsertScope: "snapshot_id", CleanupScope: "file cascade + snapshot_id", QueryFilter: "snapshot_id in active workspace snapshots"},
		{Table: "ibmi_bindings", Owner: "parser", Strategy: SnapshotStrategyScoped, Reason: "IBMi binding directory references are branch-specific resolver facts", UniqueScope: "snapshot_id, file_id, owner_object, binding_name, binding_type, target_object, target_object_type, line_number", UpsertScope: "snapshot_id", CleanupScope: "file cascade + snapshot_id", QueryFilter: "snapshot_id in active workspace snapshots"},

		{Table: "graphql_operations", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "GraphQL document operations belong to snapshot-scoped files", UniqueScope: "repo_id, file_id, operation_name, operation_type, line_number", UpsertScope: "file_id", CleanupScope: "file cascade", QueryFilter: "join files.snapshot_id"},
		{Table: "graphql_operation_usages", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "GraphQL usage rows belong to snapshot-scoped files", UniqueScope: "repo_id, file_id, import_path, imported_as, caller_function, line_number", UpsertScope: "file_id", CleanupScope: "file cascade", QueryFilter: "join files.snapshot_id"},
		{Table: "graphql_backend_entrypoints", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "GraphQL backend entrypoints belong to snapshot-scoped files", UniqueScope: "repo_id, file_id, handler_name, registration_kind, controllers_path, line_number", UpsertScope: "file_id", CleanupScope: "file cascade", QueryFilter: "join files.snapshot_id"},
		{Table: "graphql_backend_controller_links", Owner: "resolver", Strategy: SnapshotStrategyParentScoped, Reason: "links are between snapshot-scoped entrypoint and controller files", UniqueScope: "entrypoint_id, file_id", UpsertScope: "entrypoint_id, file_id", CleanupScope: "parent cascade", QueryFilter: "join parent files.snapshot_id"},
		{Table: "graphql_operation_resolvers", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "GraphQL operation resolver exports belong to snapshot-scoped controller files", UniqueScope: "repo_id, file_id, operation_name, operation_type, resolver_name, line_number", UpsertScope: "file_id", CleanupScope: "file cascade", QueryFilter: "join files.snapshot_id"},
		{Table: "graphql_operation_permissions", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "GraphQL operation permission rules belong to snapshot-scoped files", UniqueScope: "repo_id, file_id, operation_name, operation_type, rule_expression, line_number", UpsertScope: "file_id", CleanupScope: "file cascade", QueryFilter: "join files.snapshot_id"},
		{Table: "graphql_usage_operation_links", Owner: "resolver", Strategy: SnapshotStrategyParentScoped, Reason: "links are between snapshot-scoped usage and operation rows", UniqueScope: "usage_id, operation_id", UpsertScope: "usage_id, operation_id", CleanupScope: "parent cascade", QueryFilter: "join parent files.snapshot_id"},
		{Table: "azure_host_configs", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "Azure host config belongs to snapshot-scoped files", UniqueScope: "repo_id, file_id", UpsertScope: "file_id", CleanupScope: "file cascade", QueryFilter: "join files.snapshot_id"},
		{Table: "azure_function_triggers", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "Azure triggers belong to snapshot-scoped files", UniqueScope: "repo_id, file_id, trigger identity", UpsertScope: "file_id", CleanupScope: "file cascade", QueryFilter: "join files.snapshot_id"},
		{Table: "gateway_routes", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "gateway routes belong to snapshot-scoped files", UniqueScope: "repo_id, file_id, gateway identity", UpsertScope: "file_id", CleanupScope: "file cascade", QueryFilter: "join files.snapshot_id"},

		{Table: "fields", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "fields belong to snapshot-scoped classes/interfaces", UniqueScope: "parent id", UpsertScope: "class_id/interface_id", CleanupScope: "parent cascade", QueryFilter: "join parent file snapshot"},
		{Table: "annotations", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "annotations belong to snapshot-scoped entities", UniqueScope: "entity id", UpsertScope: "entity id", CleanupScope: "parent cascade", QueryFilter: "join parent file snapshot"},
		{Table: "method_signatures", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "method signatures belong to snapshot-scoped functions", UniqueScope: "function_id", UpsertScope: "function_id", CleanupScope: "function cascade", QueryFilter: "join function file snapshot"},
		{Table: "constructor_params", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "constructor params belong to snapshot-scoped classes", UniqueScope: "class_id", UpsertScope: "class_id", CleanupScope: "class cascade", QueryFilter: "join class file snapshot"},
		{Table: "type_parameters", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "type parameters belong to snapshot-scoped entities", UniqueScope: "entity id", UpsertScope: "entity id", CleanupScope: "parent cascade", QueryFilter: "join parent file snapshot"},
		{Table: "http_interface_methods", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "HTTP interface methods belong to snapshot-scoped interfaces/functions", UniqueScope: "interface_id, method_name", UpsertScope: "interface_id, method_name", CleanupScope: "parent cascade", QueryFilter: "join interface file snapshot"},
		{Table: "bean_definitions", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "bean definitions belong to snapshot-scoped classes/functions", UniqueScope: "config_class_id/method_id", UpsertScope: "parent id", CleanupScope: "parent cascade", QueryFilter: "join class file snapshot"},
		{Table: "event_listeners", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "event listeners belong to snapshot-scoped classes/functions", UniqueScope: "class_id/method_id", UpsertScope: "parent id", CleanupScope: "parent cascade", QueryFilter: "join class file snapshot"},
		{Table: "scheduled_methods", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "scheduled methods belong to snapshot-scoped classes/functions", UniqueScope: "class_id/method_id", UpsertScope: "parent id", CleanupScope: "parent cascade", QueryFilter: "join class file snapshot"},
		{Table: "jpa_entities", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "JPA entities belong to snapshot-scoped classes", UniqueScope: "class_id", UpsertScope: "class_id", CleanupScope: "class cascade", QueryFilter: "join class file snapshot"},
		{Table: "jpa_relationships", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "JPA relationships belong to snapshot-scoped classes", UniqueScope: "source_class_id", UpsertScope: "source_class_id", CleanupScope: "class cascade", QueryFilter: "join class file snapshot"},
		{Table: "synthetic_methods", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "synthetic methods belong to snapshot-scoped classes", UniqueScope: "class_id", UpsertScope: "class_id", CleanupScope: "class cascade", QueryFilter: "join class file snapshot"},
		{Table: "enum_constants", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "enum constants belong to snapshot-scoped classes", UniqueScope: "class_id, name", UpsertScope: "class_id, name", CleanupScope: "class cascade", QueryFilter: "join class file snapshot"},
		{Table: "lambda_expressions", Owner: "parser", Strategy: SnapshotStrategyParentScoped, Reason: "lambda expressions belong to snapshot-scoped files", UniqueScope: "file_id", UpsertScope: "file_id", CleanupScope: "file cascade", QueryFilter: "join files.snapshot_id"},

		{Table: "eventbridge_schedules", Owner: "extract-eventbridge", Strategy: SnapshotStrategyGlobal, Reason: "External schedule records, not source snapshot text", UniqueScope: "rule_name, target_name", UpsertScope: "supplied rule/target pairs", CleanupScope: "explicit operator maintenance", QueryFilter: "joined to snapshot-scoped SQS consumers before graph use"},
		{Table: "repo_dependency_edges", Owner: "audit", Strategy: SnapshotStrategyDerived, Reason: "legacy derived projection; graph API now derives workspace dependency graph from snapshot-scoped HTTP/SQS facts", UniqueScope: "source_repo_id, target_repo_id, edge_type, queue_name", UpsertScope: "global rebuild", CleanupScope: "global rebuild", QueryFilter: "not used for workspace-scoped dependency graph"},
	}
}
